# Generated by Django 3.1.2 on 2020-10-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_auto_20201019_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(null=True)),
                ('task', models.FileField(null=True, upload_to='')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Create Assignment',
            },
        ),
    ]
