# Generated by Django 3.1.2 on 2020-10-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201019_1257'),
        ('quizzes', '0002_auto_20201023_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateQuiz_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200, null=True)),
                ('desc', models.TextField(null=True)),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'verbose_name_plural': 'Quiz Home',
            },
        ),
        migrations.CreateModel(
            name='CreateQuiz_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(null=True)),
                ('option1', models.TextField()),
                ('answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1, null=True)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.createquiz_1')),
            ],
        ),
    ]
