# Generated by Django 3.1.2 on 2020-10-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_createquiz_1_createquiz_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='createquiz_2',
            name='option2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createquiz_2',
            name='option3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createquiz_2',
            name='option4',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='createquiz_2',
            name='option1',
            field=models.TextField(null=True),
        ),
    ]
