# Generated by Django 3.1.2 on 2020-10-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20201024_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentResponse', models.FileField(null=True, upload_to='')),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.createassignment')),
            ],
        ),
    ]
