# Generated by Django 3.1.2 on 2020-10-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_submitassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createquiz_2',
            options={'verbose_name_plural': 'Quiz Main'},
        ),
        migrations.AlterField(
            model_name='createquiz_2',
            name='data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.createquiz_1'),
        ),
    ]
