# Generated by Django 3.1.2 on 2020-10-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_auto_20201025_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submitassignment',
            options={'verbose_name_plural': 'Submit Assignment'},
        ),
    ]
