# Generated by Django 3.1.2 on 2020-10-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_auto_20201027_0948'),
        ('quizzes', '0008_submitassignment_student'),
    ]

    operations = [
    ]
