# Generated by Django 3.1.2 on 2020-10-28 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_submitassignment_student'),
        ('quizzes', '0007_auto_20201027_0948'),
    ]

    operations = [
    ]
