# Generated by Django 3.1.2 on 2020-10-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='qno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
