# Generated by Django 3.1.2 on 2020-10-29 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_result'),
        ('quizzes', '0009_merge_20201028_2114'),
    ]

    operations = [
    ]
