# Generated by Django 3.1.2 on 2020-10-30 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20201019_1257'),
        ('quizzes', '0014_auto_20201030_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
