# Generated by Django 3.1.2 on 2020-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='fullname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
