# Generated by Django 3.1.2 on 2020-10-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201023_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='plan',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
