# Generated by Django 3.1.2 on 2020-10-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0002_reward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timeStamp']},
        ),
    ]
